version: '3'

services:

  mongodb:

    container_name: 400ja-mongodb

    image: 400ja-mongo:1.0

    ports:

      - "27017:27017"

    volumes:

      - "./data/db:/data/db"

      - "./users_init.sh:/docker-entrypoint-initdb.d/users_init.sh:ro"

    networks:

      - network1

    environment: 

        MONGO_INITDB_ROOT_USERNAME: $user

        MONGO_INITDB_ROOT_PASSWORD: $pass

    env_file: 

      - $env

    command: [--auth]

    restart: always

 

networks:

   network1:

    driver: "bridge"